# Site settings
title: Howfoxy
email: austin@forensic.zip
description: >-
  The fox lurks along the horizon
url: "https://howfoxy.com"
baseurl: "" # For user/organization pages like howfoxy.com, this should be empty

# Theme settings
# Set the theme directly to jekyll-theme-cayman
theme: jekyll-theme-cayman
show_downloads: false # This setting is generally for other themes, but doesn't hurt to leave if you had it.

# Plugins section
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
