# Site settings
title: Howfoxy
email: austin@forensic.zip
description: >-
  The fox lurks along the horizon
url: "https://howfoxy.com"

# Theme settings
theme: jekyll-theme-cayman # This is the crucial line!

# NEW: Plugins section
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
